ExternalConfigs:
 # Mer configs base
  - /usr/share/kickstarter-configs/mer
  - generic
  - adaptations
  - scripts


Configurations:
  - Name: Plasma Active N900
    FileName: plasma-active-armv7hl-n900
    Inherit:
        - Plasma Active
        - Nemo Adaptation N900
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active N950
    FileName: plasma-active-armv7hl-n950
    Inherit:
        - Plasma Active
        - Nemo Adaptation N950 N9
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active Pandaboard
    FileName: plasma-active-armv7hl-pandaboard
    Inherit:
        - Plasma Active
        - Nemo Adaptation PandaBoard
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower
    PostScripts:
        - scripts/pandaboard-sw-cursor-enable.post
        - scripts/qt-graphicssystem-opengl.post
  
  - Name: Plasma Active Sunxi
    FileName: plasma-active-armv7hl-sunxi
    Inherit:
        - Plasma Active
        - Nemo Adaptation Sunxi
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower
    PostScripts:
        - scripts/pandaboard-sw-cursor-enable.post
      
  - Name: Plasma Active i586 Virtual Machine
    FileName: plasma-active-i586-vm
    RepositoryArchitecture: i586
    BootloaderTimeout: 0
    BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
    Kernel: kernel-adaptation-pc
    Part: x86.partition
    Inherit:
        - Plasma Active
        - Nemo Adaptation VM
        - SSSE3 enabled X86 architecture
    ExtraPackages:
        - acpid
        - linux-firmware
        - installer-shell
        - kernel-adaptation-pc
        - xorg-x11-drv-mtev
        - xorg-x11-drv-synaptics
        - xorg-x11-drv-intel
        - mesa-x86-generic
        - mesa-x86-generic-dri-i915-driver
        - mesa-x86-generic-dri-i965-driver
        - mesa-x86-generic-libEGL
        - mesa-x86-generic-libGLESv2
        - mesa-x86-generic-libglapi
        - nemo-mobile-configs-x86-generic
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active i486 Virtual Machine
    FileName: plasma-active-i486-vm
    BootloaderTimeout: 0
    BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
    Kernel: kernel-adaptation-pc
    Part: x86.partition
    Inherit:
        - Plasma Active
        - Nemo Adaptation VM
        - Generic X86 architecture
    ExtraPackages:
        - acpid
        - linux-firmware
        - installer-shell
        - kernel-adaptation-pc
        - xorg-x11-drv-mtev
        - xorg-x11-drv-synaptics
        - xorg-x11-drv-intel
        - mesa-x86-generic
        - mesa-x86-generic-dri-i915-driver
        - mesa-x86-generic-dri-i965-driver
        - mesa-x86-generic-libEGL
        - mesa-x86-generic-libGLESv2
        - mesa-x86-generic-libglapi
        - nemo-mobile-configs-x86-generic
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active i586
    FileName: plasma-active-i586
    RepositoryArchitecture: i586
    BootloaderTimeout: 0
    BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
    Kernel: kernel-adaptation-pc
    Part: x86.partition
    Inherit:
        - Plasma Active
        - Nemo Adaptation x86 generic
        - SSSE3 enabled X86 architecture
    ExtraPackages:
        - acpid
        - linux-firmware
        - installer-shell
        - kernel-adaptation-pc
        - xorg-x11-drv-mtev
        - xorg-x11-drv-synaptics
        - xorg-x11-drv-intel
        - mesa-x86-generic
        - mesa-x86-generic-dri-i915-driver
        - mesa-x86-generic-dri-i965-driver
        - mesa-x86-generic-libEGL
        - mesa-x86-generic-libGLESv2
        - mesa-x86-generic-libglapi
        - nemo-mobile-configs-x86-generic
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active Google Nexus7
    FileName: plasma-active-armv7hl-google-nexus7
    Inherit:
        - Plasma Active
        - Nemo Adaptation Google Nexus7
    Repos:
        - plasma-adaptation-nexus7
    ExtraPackages:
        - nexus7-fw-installer
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active Adaptation Archos Gen9 Framebuffer
    FileName: plasma-active-armv7l-archos-gen9-fb
    Inherit:
        - Plasma Active
        - Mer Extras Adaptation Archos Gen9 Framebuffer
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower

  - Name: Plasma Active Adaptation Archos Gen9 PVR
    FileName: plasma-active-armv7l-archos-gen9-pvr
    Inherit:
        - Plasma Active
        - Mer Extras Adaptation Archos Gen9 PVR
    ExtraPackages:
        - nemo-mobile-session
        - contextkit-plugin-upower

