# -*-mic2-options-*- -f loop --save-kernel -*-mic2-options-*-

#
# Do not Edit! Generated by:
# kickstarter.py
#

lang en_US.UTF-8
keyboard us
timezone --utc Europe/Berlin
rootpw mer
desktop --autologinuser=mer
user --name mer  --groups audio,video --password mer


repo --name=mer-core --baseurl=http://releases.merproject.org/releases/latest/builds/armv7hl/packages/ --save
repo --name=mer-core-debuginfo --baseurl=http://releases.merproject.org/releases/latest/builds/armv7hl/debug/ --save
repo --name=mer-shared --baseurl=http://repo.pub.meego.com/CE:/MW:/Shared/Mer_Core_armv7hl/ --save
repo --name=mer-extras --baseurl=http://repo.pub.meego.com/Project:/KDE:/Mer_Extras/CE_MW_Shared_Mer_Core_armv7hl/ --save
repo --name=plasma --baseurl=http://repo.pub.meego.com/Project:/KDE:/Devel/CE_UX_PlasmaActive_armv7hl/ --save
repo --name=adaptation-tegra3-common --baseurl=http://repo.merproject.org/obs/nemo:/devel:/hw:/nv:/tegra3:/common/latest_armv7hl/ --save
repo --name=adaptation-tegra3-nexus7 --baseurl=http://repo.merproject.org/obs/nemo:/devel:/hw:/nv:/tegra3:/nexus7/latest_armv7hl --save

%packages
# mer-core repository
####################

@Mer Core Utils
# connman-test diffutils openssh-clients vim-enhanced tar

@Mer Core
# Mer Core defines following packages (06 dec 2011)
# basesystem bash boardname coreutils deltarpm e2fsprogs file filesystem fontpackages-filesystem
# kbd lsb-release meego-release nss pam passwd prelink procps readline rootfiles rpm setup
# shadow-utils shared-mime-info systemd-sysv time udev usbutils util-linux xdg-user-dirs zypper

@Mer Connectivity
# Mer Connectivity defines following packages (06 dec 2011)
# bluez connman crda iproute iputils net-tools ofono wireless-tools wpa_supplicant

#remove connman
-connman
-connman-test

@Mer Graphics Common
# Mer Graphics Common defines following packages (06 dec 2011)
# cjkuni-fonts droid-sans-fonts droid-sans-mono-fonts droid-serif-fonts liberation-fonts-common
# liberation-mono-fonts liberation-sans-fonts liberation-serif-fonts uxlaunch

@Mer Minimal Xorg
# Mer Minimal Xorg defines following packages (06 dec 2011)
# xorg-x11-server-Xorg xorg-x11-xauth

# Additional packages from mercore repository
cpio
gzip
tar
openssh-server
libqtwebkit-qmlwebkitplugin
xorg-x11-drv-evdev
xorg-x11-drv-fbdev
xorg-x11-drv-vesa
xorg-x11-utils-xhost
# get virtualbox running
xorg-x11-server-Xorg-setuid
# FIXME - packages should explicitly depend on it
dbus-x11
libqtwebkit-qmlwebkitplugin
libqtdeclarative4-gestures
libqtdeclarative4-particles
libdeclarative-multimedia
alsa-utils
upower


# mer-shared repository
#######################

# Additional packages from mer-shared repository
gdb
gst-plugins-good
ca-certificates
pulseaudio-policy-enforcement

# plasma repository
###################
contour
contour-intro-tegra3
declarative-plasmoids
kdelibs-data
kdelibs-imageio-plugins
kdelibs-plasma-runtime
kdepim-strigi-plugins
kde-runtime-desktoptheme
kde-runtime-emoticons
kde-runtime-nepomuk
kde-runtime-netattach
kde-runtime-newstuff
kde-runtime-plasma
kde-runtime-solid
kde-runtime-sounds
kde-runtime-wallet
konsole
kmix
plasma-active
plasma-mobile-mouse
startactive
virtuoso
virtuoso-drivers
virtuoso-server
# Required by kde-workspace crash helper tool installdbgsymbols.sh
kdialog
# add some simple testing tools
simple-tests
sample-media-tegra3
ConsoleKit
ConsoleKit-libs
ConsoleKit-x11
dhclient
libpcap
ModemManager
NetworkManager
NetworkManager-glib
NetworkManager-kde
NetworkManager-kde-libs
plasmoid-networkmanagement

# add kde-security packages
encfs
fuse
rlog

# Games
lskat
katomic
kfourinline
knetwalk
kshisen
kmahjongg
kpat
kreversi


# Apps
bangarang
kwrite


# adaptation nexus7 repository
###################################
codecs-tegra3
graphics-adaptation-tegra3
graphics-adaptation-tegra3-libEGL
graphics-adaptation-tegra3-libGLESv1
graphics-adaptation-tegra3-libGLESv2
graphics-adaptation-tegra3-libOMX
#graphics-adaptation-tegra-tools
graphics-adaptation-tegra3-xorg
kernel-adaptation-google-nexus7
moslo-nexus7
linux-firmware-tegra3
mtdev
xorg-x11-drv-mtev
configs-tegra3
configs-nexus7

# mer-extras repository
#######################
alsa-plugins-pulseaudio
less
strace
xorg-x11-drv-mtev
iodbc

-okular

%end


%post
# save a little bit of space at least...
rm -f /boot/initrd*

# Prelink can reduce boot time
if [ -x /usr/sbin/prelink ]; then
    /usr/sbin/prelink -aRqm
fi

rm -f /var/lib/rpm/__db*
rpm --rebuilddb

# Create empty initramfs.cpio.lzo for NAND deployment
touch /boot/initramfs.cpio.lzo

# Create a session file x-plasma-active.desktop
echo "[Desktop Entry]" >> /usr/share/xsessions/x-plasma-active.desktop
echo "Version=1.0" >> /usr/share/xsessions/x-plasma-active.desktop
echo "Name=mtf compositor session" >> /usr/share/xsessions/x-plasma-active.desktop
echo "Exec=/usr/bin/startactive" >> /usr/share/xsessions/x-plasma-active.desktop
echo "Type=Application" >> /usr/share/xsessions/x-plasma-active.desktop

# Set symlink pointing to .desktop file 
ln -sf x-plasma-active.desktop /usr/share/xsessions/default.desktop

# Set arch to armv7hl for zypper.
echo "arch = armv7hl" >> /etc/zypp/zypp.conf

%end

%post --nochroot
if [ -n "" ]; then
    echo "BUILD: " >> /etc/meego-release
fi

%end
